# Generated by Django 4.0.4 on 2022-09-17 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studymain', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
